"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { ptBR, enUS, es, it } from 'date-fns/locale';

type Language = 'pt' | 'en' | 'es' | 'it';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, params?: Record<string, string | number>) => string;
    locale: any; // date-fns locale
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('pt');

    useEffect(() => {
        const storedLanguage = localStorage.getItem("finance_language") as Language;
        if (storedLanguage) {
            setLanguage(storedLanguage);
        }
    }, []);

    const handleSetLanguage = (newLanguage: Language) => {
        setLanguage(newLanguage);
        localStorage.setItem("finance_language", newLanguage);
    };

    const locales = {
        pt: ptBR,
        en: enUS,
        es: es,
        it: it
    };

    const translations: Record<Language, Record<string, string>> = {
        pt: {
            // General
            welcome: "Bem-vindo de volta!",
            overview: "Visão Geral",
            personal: "Pessoal",
            business: "Empresarial",
            total: "Total",
            save: "Salvar",
            cancel: "Cancelar",
            edit: "Editar",
            delete: "Excluir",
            back: "Voltar",
            optional: "Opcional",
            select: "Selecione...",

            // Sidebar
            dashboard: "Dashboard",
            transactions: "Transações",
            wallet: "Minha Carteira",
            calendar: "Calendário",
            reports: "Relatórios",
            planning: "Planejamento",
            income: "Renda",
            settings: "Configurações",
            new_transaction: "Nova Transação",
            logout: "Sair (Bloquear)",
            user: "Usuário",

            // Dashboard
            my_cards: "Meus Cartões",
            view_all: "Ver todos",
            cash_flow: "Fluxo de Caixa",
            last_6_months: "Últimos 6 meses",
            total_balance: "Saldo Atual",
            balance: "Saldo em Contas",
            current_balance: "Saldo Atual",
            income_month: "Receitas (Este Mês)",
            expense_month: "Despesas (Este Mês)",
            upcoming_bills: "Contas da Semana",
            total_to_pay: "Total a pagar",
            no_bills: "Nenhuma conta para esta semana 🎉",
            my_goals: "Meus Objetivos",
            manage_goals: "Gerenciar Objetivos",
            recent_transactions: "Transações Recentes",

            // Cards
            current_invoice: "Fatura Atual",
            available_limit: "Limite Disponível",
            limit_usage: "Uso do Limite",
            limit: "Limite",
            available: "Disponível",
            closes_day: "Fecha dia",
            due_day: "Vence dia",
            best_buy_day: "MELHOR DIA DE COMPRA",
            view_invoice: "Ver Fatura",
            card_holder: "Titular",
            bank: "Banco",
            wallet_subtitle: "Gerencie seus cartões e limites",
            new_card: "Novo Cartão",
            new_account: "Nova Conta",
            new_document: "Novo Documento",
            credit_cards: "Cartões de Crédito",
            bank_accounts: "Contas Bancárias",
            documents: "Documentos",
            personal_context: "Pessoal",
            business_context: "Empresarial",

            // Forms
            edit_transaction: "Editar Transação",
            new_income: "Nova Renda",
            received: "Recebido",
            paid: "Pago",
            to_receive: "A Receber",
            pending: "Pendente",
            expense: "Despesa",
            revenue: "Receita",
            recurrence: "Recorrência",
            enable: "Habilitar",
            fixed_charge: "Cobrança Recorrente",
            type_fixed_help: "Esta opção é para utilizar em recorrências de Aluguel, Conta de água, Conta de luz...",
            consumes_limit: "Consome o limite total do cartão (de cartão de crédito).",
            subscription: "Assinatura",
            type_sub_help: "Esta opção é para assinaturas digitais com cobranças mensais...",
            no_consume_limit: "Não consome o limite futuro, apenas o mês atual.",
            amount: "Valor",
            description: "Descrição",
            category: "Categoria",
            brand: "Marca / Empresa",
            select_brand: "Selecione uma marca...",
            date: "Data",
            payment_method: "Método de Pagamento",
            account: "Conta Bancária",
            select_account: "Selecione a conta...",
            card: "Cartão",
            select_card: "Selecione o cartão...",
            installments: "Quantidade de Parcelas",
            save_changes: "Salvar Alterações",
            save_transaction: "Salvar Transação",
            credit: "Crédito",
            debit: "Débito",
            pix: "Pix",
            cash: "Dinheiro",
            transfer: "Transferência",
            boleto: "Boleto",
            installment_prefix: "Parcela",

            // Icons
            icon_target: "Alvo",
            icon_plane: "Avião",
            icon_car: "Carro",
            icon_home: "Casa",
            icon_star: "Estrela",
            icon_shield: "Escudo",
            // Colors
            color_blue: "Azul",
            color_green: "Verde",
            color_orange: "Laranja",
            color_purple: "Roxo",
            color_red: "Vermelho",

            // Goal Actions
            add_value: "Lançar Valor",
            history: "Histórico",
            deposit_to: "Depósito para",
            source_account: "Conta de Origem",
            confirm: "Confirmar",


            confirm_delete_card: "Tem certeza que deseja excluir o cartão {cardName}?",
            card_deleted_success: "Cartão {cardName} excluído com sucesso!",
            edit_card: "Editar Cartão",
            delete_card: "Excluir Cartão",
            dashboard_subtitle: "Visão geral das suas finanças",
            transactions_subtitle: "Histórico completo de movimentações",
            search_placeholder: "Buscar transações...",
            all: "Todas",
            all_categories: "Todas Categorias",
            all_methods: "Todos Métodos",
            no_transactions_found: "Nenhuma transação encontrada",
            no_transactions_help: "Tente ajustar os filtros ou adicione uma nova transação.",
            new: "Novo",
            all_caught_up: "Tudo em dia!",
            no_pending_bills_7_days: "Nenhuma conta pendente para os próximos 7 dias.",
            upcoming_bills_title: "Contas da Semana",
            pending_count: "{count} pendentes",
            mark_as_paid_confirm: "Deseja marcar \"{description}\" como pago?",
            pay_now: "Pagar Agora",
            today: "Hoje",
            tomorrow: "Amanhã",

            // Settings
            settings_title: "Configurações",
            settings_subtitle: "Personalize sua experiência e gerencie seus dados",
            appearance_language: "Aparência e Idioma",
            theme: "Tema",
            light: "Claro",
            dark: "Escuro",
            entrepreneur: "Empreendedora",
            language: "Idioma",
            data_management: "Gerenciamento de Dados",
            export_backup: "Exportar Backup",
            export_backup_desc: "Baixe uma cópia de segurança dos seus dados.",
            export: "Exportar",
            danger_zone: "Zona de Perigo",
            delete_transactions: "Apagar Transações",
            delete_transactions_desc: "Remove apenas o histórico financeiro.",
            delete_cards: "Apagar Cartões",
            delete_cards_desc: "Remove todos os cartões cadastrados.",
            delete_all: "Apagar TUDO (Resetar App)",
            delete_all_desc: "Remove todos os dados, perfil e configurações. Irreversível.",
            delete_confirmation_title: "Tem certeza absoluta?",
            delete_confirmation_desc: "Esta ação não pode ser desfeita. Isso excluirá permanentemente os dados selecionados.",
            type_delete_instruction: "Digite DELETAR para confirmar",
            erase: "Apagar",
            backup_success: "Backup exportado com sucesso!",
            wrong_confirmation: "Palavra de confirmação incorreta.",
            data_deleted: "Dados apagados com sucesso! Recarregando...",

            // Goals
            new_goal: "Novo Objetivo",
            edit_goal: "Editar Objetivo",
            confirm_delete_goal: "Tem certeza que deseja excluir este objetivo?",
            goal_name: "Nome do Objetivo",
            target_amount: "Valor Alvo",
            current_amount: "Valor Atual",
            icon: "Ícone",
            color: "Cor",
            no_goals_yet: "Nenhum objetivo definido ainda",
            create_goal: "Criar um objetivo",
            of: "de",

            // Calendar
            calendar_title: "Calendário",
            calendar_subtitle: "Visualize seus vencimentos e receitas",
            invoice: "Fatura",
            todays_invoices: "Faturas do Dia",
            due_today: "Vencimento Hoje",
            entries: "Lançamentos",
            inflows: "Entradas",
            outflows: "Saídas",
            no_entries_day: "Nenhum lançamento ou fatura para este dia.",

            // Reports
            reports_title: "Relatórios",
            reports_subtitle: "Análise detalhada das suas finanças",
            spending_by_category: "Gastos por Categoria",
            income_vs_expense: "Receita vs Despesa (Últimos 6 meses)",
            not_enough_data: "Sem dados suficientes",

            // Planning
            planning_title: "Planejamento Futuro",
            planning_subtitle: "Ferramentas para alcançar sua liberdade financeira",
            debt_management: "Gestão de Dívidas",
            investments: "Investimentos",
            life_goals: "Metas de Vida",
            add_debt: "Adicionar Dívida",
            debt_name_placeholder: "Nome (ex: Cartão X)",
            value_placeholder: "Valor",
            interest_monthly_placeholder: "Juros Mensal (%)",
            add: "Adicionar",
            total_debts: "Total em Dívidas",
            snowball_strategy: "Sua Lista (Estratégia Bola de Neve)",
            snowball_desc: "Recomendamos pagar primeiro as dívidas com maiores juros ou menores valores.",
            no_debts: "Nenhuma dívida cadastrada. Parabéns!",
            interest_rate_month: "% a.m.",
            compound_interest_sim: "Simulador de Juros Compostos",
            initial_investment: "Investimento Inicial",
            monthly_contribution: "Aporte Mensal",
            interest_rate_year: "Taxa de Juros (% ao ano)",
            time_years: "Tempo (anos)",
            total_accumulated: "Total Acumulado",
            total_invested: "Total Investido",
            yield_interest: "Rendimento (Juros)",
            goals_coming_soon: "Em breve você poderá criar metas visuais para comprar sua casa, carro ou fazer aquela viagem dos sonhos.",

            // Income
            income_title: "Renda",
            income_subtitle: "Gerencie seus recebimentos e salários",
            new_income_button: "Nova Renda",
            total_received_general: "Total Recebido (Geral)",
            this_month: "Este Mês",
            income_history: "Histórico de Recebimentos",
        },
        en: {
            // General
            welcome: "Welcome back!",
            overview: "Overview",
            personal: "Personal",
            business: "Business",
            total: "Total",
            save: "Save",
            cancel: "Cancel",
            edit: "Edit",
            delete: "Delete",
            back: "Back",
            optional: "Optional",
            select: "Select...",

            // Sidebar
            dashboard: "Dashboard",
            transactions: "Transactions",
            wallet: "My Wallet",
            calendar: "Calendar",
            reports: "Reports",
            planning: "Planning",
            income: "Income",
            settings: "Settings",
            new_transaction: "New Transaction",
            logout: "Logout (Lock)",
            user: "User",

            // Dashboard
            my_cards: "My Cards",
            view_all: "View all",
            cash_flow: "Cash Flow",
            last_6_months: "Last 6 months",
            total_balance: "Current Balance",
            income_month: "Income (This Month)",
            expense_month: "Expenses (This Month)",
            upcoming_bills: "Upcoming Bills",
            total_to_pay: "Total to pay",
            no_bills: "No bills for this week 🎉",
            my_goals: "My Goals",
            manage_goals: "Manage Goals",
            recent_transactions: "Recent Transactions",
            confirm_delete_card: "Are you sure you want to delete the card {cardName}?",
            card_deleted_success: "Card {cardName} deleted successfully!",
            edit_card: "Edit Card",
            delete_card: "Delete Card",
            dashboard_subtitle: "Overview of your finances",
            all_caught_up: "All caught up!",
            no_pending_bills_7_days: "No pending bills for the next 7 days.",
            upcoming_bills_title: "Upcoming Bills",
            pending_count: "{count} pending",
            mark_as_paid_confirm: "Do you want to mark \"{description}\" as paid?",
            pay_now: "Pay Now",
            today: "Today",
            tomorrow: "Tomorrow",
            transactions_subtitle: "Complete history of transactions",
            search_placeholder: "Search transactions...",
            all: "All",
            all_categories: "All Categories",
            all_methods: "All Methods",
            no_transactions_found: "No transactions found",
            no_transactions_help: "Try adjusting filters or add a new transaction.",
            new: "New",

            // Cards
            current_invoice: "Current Invoice",
            available_limit: "Available Limit",
            limit_usage: "Limit Usage",
            limit: "Limit",
            available: "Available",
            closes_day: "Closes on",
            due_day: "Due on",
            best_buy_day: "BEST BUY DAY",
            view_invoice: "View Invoice",
            card_holder: "Holder",
            bank: "Bank",
            wallet_subtitle: "Manage your cards and limits",
            new_card: "New Card",
            new_account: "New Account",
            new_document: "New Document",
            credit_cards: "Credit Cards",
            bank_accounts: "Bank Accounts",
            documents: "Documents",
            personal_context: "Personal",
            business_context: "Business",

            // Forms
            edit_transaction: "Edit Transaction",
            new_income: "New Income",
            received: "Received",
            paid: "Paid",
            to_receive: "To Receive",
            pending: "Pending",
            expense: "Expense",
            revenue: "Revenue",
            recurrence: "Recurrence",
            enable: "Enable",
            fixed_charge: "Fixed Charge",
            type_fixed_help: "Use this for Rent, Water bill, Electricity bill...",
            consumes_limit: "Consumes total credit card limit.",
            subscription: "Subscription",
            type_sub_help: "Use this for digital subscriptions with monthly charges...",
            no_consume_limit: "Does not consume future limit, only current month.",
            amount: "Amount",
            description: "Description",
            category: "Category",
            brand: "Brand / Company",
            select_brand: "Select a brand...",
            date: "Date",
            payment_method: "Payment Method",
            account: "Bank Account",
            select_account: "Select account...",
            card: "Card",
            installments: "Installments",
            save_changes: "Save Changes",
            save_transaction: "Save Transaction",
            credit: "Credit",
            debit: "Debit",
            pix: "Pix",
            cash: "Cash",
            transfer: "Transfer",
            installment_prefix: "Installment",

            // Icons
            icon_target: "Target",
            icon_plane: "Plane",
            icon_car: "Car",
            icon_home: "Home",
            icon_star: "Star",
            icon_shield: "Shield",
            // Colors
            color_blue: "Blue",
            color_green: "Green",
            color_orange: "Orange",
            color_purple: "Purple",
            color_red: "Red",

            // Goal Actions
            add_value: "Add Value",
            history: "History",
            deposit_to: "Deposit to",
            source_account: "Source Account",
            confirm: "Confirm",




            // Settings
            settings_title: "Settings",
            settings_subtitle: "Customize your experience and manage your data",
            appearance_language: "Appearance & Language",
            theme: "Theme",
            light: "Light",
            dark: "Dark",
            entrepreneur: "Entrepreneur",
            language: "Language",
            data_management: "Data Management",
            export_backup: "Export Backup",
            export_backup_desc: "Download a backup of your data.",

            // Goals
            new_goal: "New Goal",
            edit_goal: "Edit Goal",
            confirm_delete_goal: "Are you sure you want to delete this goal?",
            goal_name: "Goal Name",
            target_amount: "Target Amount",
            current_amount: "Current Amount",
            icon: "Icon",
            color: "Color",
            no_goals_yet: "No goals yet",
            create_goal: "Create a goal",
            of: "of",

            // Calendar
            calendar_title: "Calendar",
            calendar_subtitle: "View your due dates and income",
            invoice: "Invoice",
            todays_invoices: "Today's Invoices",
            due_today: "Due Today",
            entries: "Entries",
            inflows: "Inflows",
            outflows: "Outflows",
            no_entries_day: "No entries or invoices for this day.",

            // Reports
            reports_title: "Reports",
            reports_subtitle: "Detailed analysis of your finances",
            spending_by_category: "Spending by Category",
            income_vs_expense: "Income vs Expense (Last 6 months)",
            not_enough_data: "Not enough data",

            // Planning
            planning_title: "Future Planning",
            planning_subtitle: "Tools to achieve your financial freedom",
            debt_management: "Debt Management",
            investments: "Investments",
            life_goals: "Life Goals",
            add_debt: "Add Debt",
            debt_name_placeholder: "Name (e.g. Card X)",
            value_placeholder: "Value",
            interest_monthly_placeholder: "Monthly Interest (%)",
            add: "Add",
            total_debts: "Total Debts",
            snowball_strategy: "Your List (Snowball Strategy)",
            snowball_desc: "We recommend paying off debts with higher interest or lower values first.",
            no_debts: "No debts registered. Congratulations!",
            interest_rate_month: "% p.m.",
            compound_interest_sim: "Compound Interest Simulator",
            initial_investment: "Initial Investment",
            monthly_contribution: "Monthly Contribution",
            interest_rate_year: "Interest Rate (% per year)",
            time_years: "Time (years)",
            total_accumulated: "Total Accumulated",
            total_invested: "Total Invested",
            yield_interest: "Yield (Interest)",
            goals_coming_soon: "Soon you will be able to create visual goals to buy your house, car or take that dream trip.",

            // Income
            income_title: "Income",
            income_subtitle: "Manage your earnings and salaries",
            new_income_button: "New Income",
            total_received_general: "Total Received (General)",
            this_month: "This Month",
            income_history: "Income History",
            export: "Export",
            danger_zone: "Danger Zone",
            delete_transactions: "Delete Transactions",
            delete_transactions_desc: "Removes only financial history.",
            delete_cards: "Delete Cards",
            delete_cards_desc: "Removes all registered cards.",
            delete_all: "Delete ALL (Reset App)",
            delete_all_desc: "Removes all data, profile and settings. Irreversible.",
            delete_confirmation_title: "Are you absolutely sure?",
            delete_confirmation_desc: "This action cannot be undone. This will permanently delete the selected data.",
            type_delete_instruction: "Type DELETAR to confirm",
            erase: "Erase",
            backup_success: "Backup exported successfully!",
            wrong_confirmation: "Incorrect confirmation word.",
            data_deleted: "Data erased successfully! Reloading...",
        },
        es: {
            // General
            welcome: "¡Bienvenido de nuevo!",
            overview: "Visión General",
            personal: "Personal",
            business: "Empresarial",
            total: "Total",
            save: "Guardar",
            cancel: "Cancelar",
            edit: "Editar",
            delete: "Eliminar",
            back: "Volver",
            optional: "Opcional",
            select: "Seleccionar...",

            // Sidebar
            dashboard: "Panel",
            transactions: "Transacciones",
            wallet: "Mi Billetera",
            calendar: "Calendario",
            reports: "Reportes",
            planning: "Planificación",
            income: "Ingresos",
            settings: "Configuración",
            new_transaction: "Nueva Transacción",
            logout: "Salir (Bloquear)",
            user: "Usuario",

            // Dashboard
            my_cards: "Mis Tarjetas",
            view_all: "Ver todos",
            cash_flow: "Flujo de Caja",
            last_6_months: "Últimos 6 meses",
            total_balance: "Saldo Actual",
            income_month: "Ingresos (Este Mes)",
            expense_month: "Gastos (Este Mes)",
            upcoming_bills: "Cuentas de la Semana",
            total_to_pay: "Total a pagar",
            no_bills: "No hay cuentas para esta semana 🎉",
            my_goals: "Mis Objetivos",
            manage_goals: "Gestionar Objetivos",
            recent_transactions: "Transacciones Recientes",
            confirm_delete_card: "¿Estás seguro de que deseas eliminar la tarjeta {cardName}?",
            card_deleted_success: "¡Tarjeta {cardName} eliminada con éxito!",
            edit_card: "Editar Tarjeta",
            delete_card: "Eliminar Tarjeta",
            dashboard_subtitle: "Visión general de sus finanzas",
            all_caught_up: "¡Todo al día!",
            no_pending_bills_7_days: "No hay facturas pendientes para los próximos 7 días.",
            upcoming_bills_title: "Facturas de la Semana",
            pending_count: "{count} pendientes",
            mark_as_paid_confirm: "¿Desea marcar \"{description}\" como pagado?",
            pay_now: "Pagar Ahora",
            today: "Hoy",
            tomorrow: "Mañana",
            transactions_subtitle: "Historial completo de transacciones",
            search_placeholder: "Buscar transacciones...",
            all: "Todas",
            all_categories: "Todas las Categorías",
            all_methods: "Todos los Métodos",
            no_transactions_found: "No se encontraron transacciones",
            no_transactions_help: "Intente ajustar los filtros o agregue una nueva transacción.",
            new: "Nuevo",

            // Cards
            current_invoice: "Factura Actual",
            available_limit: "Límite Disponible",
            limit_usage: "Uso del Límite",
            limit: "Límite",
            available: "Disponible",
            closes_day: "Cierra el",
            due_day: "Vence el",
            best_buy_day: "MEJOR DÍA DE COMPRA",
            view_invoice: "Ver Factura",
            card_holder: "Titular",
            bank: "Banco",
            wallet_subtitle: "Gestiona tus tarjetas y límites",
            new_card: "Nueva Tarjeta",
            new_account: "Nueva Cuenta",
            new_document: "Nuevo Documento",
            credit_cards: "Tarjetas de Crédito",
            bank_accounts: "Cuentas Bancarias",
            documents: "Documentos",
            personal_context: "Personal",
            business_context: "Empresarial",

            // Forms
            edit_transaction: "Editar Transacción",
            new_income: "Nuevo Ingreso",
            received: "Recibido",
            paid: "Pagado",
            to_receive: "Por Recibir",
            pending: "Pendiente",
            expense: "Gasto",
            revenue: "Ingreso",
            recurrence: "Recurrencia",
            enable: "Habilitar",
            fixed_charge: "Cargo Fijo",
            type_fixed_help: "Usa esto para Alquiler, Agua, Luz...",
            consumes_limit: "Consume el límite total de la tarjeta.",
            subscription: "Suscripción",
            type_sub_help: "Usa esto para suscripciones digitales...",
            no_consume_limit: "No consume límite futuro, solo el mes actual.",
            amount: "Monto",
            description: "Descripción",
            category: "Categoría",
            brand: "Marca / Empresa",
            select_brand: "Seleccionar marca...",
            date: "Fecha",
            payment_method: "Método de Pago",
            account: "Cuenta Bancaria",
            select_account: "Seleccionar cuenta...",
            card: "Tarjeta",
            installments: "Cuotas",
            save_changes: "Guardar Cambios",
            save_transaction: "Guardar Transacción",
            credit: "Crédito",
            debit: "Débito",
            pix: "Pix",
            cash: "Efectivo",
            transfer: "Transferencia",
            installment_prefix: "Cuota",

            // Icons
            icon_target: "Objetivo",
            icon_plane: "Avión",
            icon_car: "Coche",
            icon_home: "Casa",
            icon_star: "Estrella",
            icon_shield: "Escudo",
            // Colors
            color_blue: "Azul",
            color_green: "Verde",
            color_orange: "Naranja",
            color_purple: "Púrpura",
            color_red: "Rojo",

            // Goal Actions
            add_value: "Añadir Valor",
            history: "Historial",
            deposit_to: "Depósito para",
            source_account: "Cuenta de Origen",
            confirm: "Confirmar",

            // Goals
            new_goal: "Nuevo Objetivo",
            edit_goal: "Editar Objetivo",
            confirm_delete_goal: "¿Estás seguro de que quieres eliminar este objetivo?",
            goal_name: "Nombre del Objetivo",
            target_amount: "Monto Objetivo",
            current_amount: "Monto Actual",
            icon: "Icono",
            color: "Color",
            no_goals_yet: "Aún no hay objetivos",
            create_goal: "Crear un objetivo",
            of: "de",
            day: "Día",


            // Settings
            settings_title: "Configuración",
            settings_subtitle: "Personaliza tu experiencia y gestiona tus datos",
            appearance_language: "Apariencia e Idioma",
            theme: "Tema",
            light: "Claro",
            dark: "Oscuro",
            entrepreneur: "Emprendedora",
            language: "Idioma",
            data_management: "Gestión de Datos",
            export_backup: "Exportar Copia de Seguridad",
            export_backup_desc: "Descarga una copia de seguridad de tus datos.",

            // Calendar
            calendar_title: "Calendario",
            calendar_subtitle: "Visualiza tus vencimientos e ingresos",
            invoice: "Factura",
            todays_invoices: "Facturas de Hoy",
            due_today: "Vence Hoy",
            entries: "Entradas",
            inflows: "Ingresos",
            outflows: "Egresos",
            no_entries_day: "No hay entradas o facturas para este día.",

            // Reports
            reports_title: "Reportes",
            reports_subtitle: "Análisis detallado de tus finanzas",
            spending_by_category: "Gastos por Categoría",
            income_vs_expense: "Ingresos vs Gastos (Últimos 6 meses)",
            not_enough_data: "No hay suficientes datos",

            // Planning
            planning_title: "Planificación Futura",
            planning_subtitle: "Herramientas para alcanzar tu libertad financiera",
            debt_management: "Gestión de Deudas",
            investments: "Inversiones",
            life_goals: "Metas de Vida",
            add_debt: "Agregar Deuda",
            debt_name_placeholder: "Nombre (ej: Tarjeta X)",
            value_placeholder: "Valor",
            interest_monthly_placeholder: "Interés Mensual (%)",
            add: "Agregar",
            total_debts: "Total en Deudas",
            snowball_strategy: "Tu Lista (Estrategia Bola de Nieve)",
            snowball_desc: "Recomendamos pagar primero las deudas con mayores intereses o menores valores.",
            no_debts: "No hay deudas registradas. ¡Felicitaciones!",
            interest_rate_month: "% p.m.",
            compound_interest_sim: "Simulador de Interés Compuesto",
            initial_investment: "Inversión Inicial",
            monthly_contribution: "Aporte Mensual",
            interest_rate_year: "Tasa de Interés (% anual)",
            time_years: "Tiempo (años)",
            total_accumulated: "Total Acumulado",
            total_invested: "Total Invertido",
            yield_interest: "Rendimiento (Interés)",
            goals_coming_soon: "Pronto podrás crear metas visuales para comprar tu casa, auto o hacer ese viaje soñado.",

            // Income
            income_title: "Ingresos",
            income_subtitle: "Administra tus cobros y salarios",
            new_income_button: "Nuevo Ingreso",
            total_received_general: "Total Recibido (General)",
            this_month: "Este Mes",
            income_history: "Historial de Ingresos",
            export: "Exportar",
            danger_zone: "Zona de Peligro",
            delete_transactions: "Borrar Transacciones",
            delete_transactions_desc: "Elimina solo el historial financiero.",
            delete_cards: "Borrar Tarjetas",
            delete_cards_desc: "Elimina todas las tarjetas registradas.",
            delete_all: "Borrar TODO (Reiniciar App)",
            delete_all_desc: "Elimina todos los datos, perfil y configuraciones. Irreversible.",
            delete_confirmation_title: "¿Estás absolutamente seguro?",
            delete_confirmation_desc: "Esta acción no se puede deshacer. Esto eliminará permanentemente los datos seleccionados.",
            type_delete_instruction: "Escribe DELETAR para confirmar",
            erase: "Borrar",
            backup_success: "¡Copia de seguridad exportada con éxito!",
            wrong_confirmation: "Palabra de confirmación incorrecta.",
            data_deleted: "¡Datos borrados con éxito! Recargando...",
        },
        it: {
            // General
            welcome: "Bentornato!",
            overview: "Panoramica",
            personal: "Personale",
            business: "Aziendale",
            total: "Totale",
            save: "Salva",
            cancel: "Annulla",
            edit: "Modifica",
            delete: "Elimina",
            back: "Indietro",
            optional: "Opzionale",
            select: "Seleziona...",

            // Sidebar
            dashboard: "Dashboard",
            transactions: "Transazioni",
            wallet: "Il mio Portafoglio",
            calendar: "Calendario",
            reports: "Report",
            planning: "Pianificazione",
            income: "Reddito",
            settings: "Impostazioni",
            new_transaction: "Nuova Transazione",
            logout: "Esci (Blocca)",
            user: "Utente",

            // Dashboard
            my_cards: "Le mie Carte",
            view_all: "Vedi tutti",
            cash_flow: "Flusso di Cassa",
            last_6_months: "Ultimi 6 mesi",
            total_balance: "Saldo Attuale",
            income_month: "Entrate (Questo Mese)",
            expense_month: "Uscite (Questo Mese)",
            upcoming_bills: "Bollette della Settimana",
            total_to_pay: "Totale da pagare",
            no_bills: "Nessuna bolletta per questa settimana 🎉",
            my_goals: "I miei Obiettivi",
            manage_goals: "Gestisci Obiettivi",
            recent_transactions: "Transazioni Recenti",
            confirm_delete_card: "Sei sicuro di voler eliminare la carta {cardName}?",
            card_deleted_success: "Carta {cardName} eliminata con successo!",
            edit_card: "Modifica Carta",
            delete_card: "Elimina Carta",
            dashboard_subtitle: "Panoramica delle tue finanze",
            all_caught_up: "Tutto aggiornato!",
            no_pending_bills_7_days: "Nessuna fattura in sospeso per i prossimi 7 giorni.",
            upcoming_bills_title: "Fatture della Settimana",
            pending_count: "{count} in sospeso",
            mark_as_paid_confirm: "Vuoi segnare \"{description}\" come pagato?",
            pay_now: "Paga Ora",
            today: "Oggi",
            tomorrow: "Domani",
            transactions_subtitle: "Cronologia completa delle transazioni",
            search_placeholder: "Cerca transazioni...",
            all: "Tutte",
            all_categories: "Tutte le Categorie",
            all_methods: "Tutti i Metodi",
            no_transactions_found: "Nessuna transazione trovata",
            no_transactions_help: "Prova a modificare i filtri o aggiungi una nuova transazione.",
            new: "Nuovo",

            // Cards
            current_invoice: "Fattura Attuale",
            available_limit: "Limite Disponibile",
            limit_usage: "Uso del Limite",
            limit: "Limite",
            available: "Disponibile",
            closes_day: "Chiude il",
            due_day: "Scade il",
            best_buy_day: "MIGLIOR GIORNO D'ACQUISTO",
            view_invoice: "Vedi Fattura",
            card_holder: "Titolare",
            bank: "Banca",
            wallet_subtitle: "Gestisci le tue carte e i limiti",
            new_card: "Nuova Carta",
            new_account: "Nuovo Conto",
            new_document: "Nuovo Documento",
            credit_cards: "Carte di Credito",
            bank_accounts: "Conti Bancari",
            documents: "Documenti",
            personal_context: "Personale",
            business_context: "Aziendale",

            // Forms
            edit_transaction: "Modifica Transazione",
            new_income: "Nuova Entrata",
            received: "Ricevuto",
            paid: "Pagato",
            to_receive: "Da Ricevere",
            pending: "In Sospeso",
            expense: "Spesa",
            revenue: "Entrata",
            recurrence: "Ricorrenza",
            enable: "Abilita",
            fixed_charge: "Addebito Fisso",
            type_fixed_help: "Usa questo per Affitto, Acqua, Luce...",
            consumes_limit: "Consuma il limite totale della carta.",
            subscription: "Abbonamento",
            type_sub_help: "Usa questo per abbonamenti digitali...",
            no_consume_limit: "Non consuma limite futuro, solo mese corrente.",
            amount: "Importo",
            description: "Descrizione",
            category: "Categoria",
            brand: "Marca / Azienda",
            select_brand: "Seleziona marca...",
            date: "Data",
            payment_method: "Metodo di Pagamento",
            account: "Conto Bancario",
            select_account: "Seleziona conto...",
            card: "Carta",
            installments: "Rate",
            save_changes: "Salva Modifiche",
            save_transaction: "Salva Transazione",
            credit: "Credito",
            debit: "Debito",
            pix: "Pix",
            cash: "Contanti",
            transfer: "Bonifico",
            installment_prefix: "Rata",

            // Icons
            icon_target: "Obiettivo",
            icon_plane: "Aereo",
            icon_car: "Auto",
            icon_home: "Casa",
            icon_star: "Stella",
            icon_shield: "Scudo",
            // Colors
            color_blue: "Blu",
            color_green: "Verde",
            color_orange: "Arancione",
            color_purple: "Viola",
            color_red: "Rosso",

            // Goal Actions
            add_value: "Aggiungi Valore",
            history: "Cronologia",
            deposit_to: "Deposito per",
            source_account: "Conto di Origine",
            confirm: "Conferma",

            // Goals
            new_goal: "Nuovo Obiettivo",
            edit_goal: "Modifica Obiettivo",
            confirm_delete_goal: "Sei sicuro di voler eliminare questo obiettivo?",
            goal_name: "Nome dell'Obiettivo",
            target_amount: "Importo Obiettivo",
            current_amount: "Importo Attuale",
            icon: "Icona",
            color: "Colore",
            no_goals_yet: "Nessun obiettivo ancora",
            create_goal: "Crea un obiettivo",
            of: "di",
            day: "Giorno",

            // Settings
            settings_title: "Impostazioni",
            settings_subtitle: "Personalizza la tua esperienza e gestisci i tuoi dati",
            appearance_language: "Aspetto e Lingua",
            theme: "Tema",
            light: "Chiaro",
            dark: "Scuro",
            entrepreneur: "Imprenditrice",
            language: "Lingua",
            data_management: "Gestione Dati",
            export_backup: "Esporta Backup",
            export_backup_desc: "Scarica un backup dei tuoi dati.",

            // Calendar
            calendar_title: "Calendario",
            calendar_subtitle: "Visualizza le tue scadenze e entrate",
            invoice: "Fattura",
            todays_invoices: "Fatture di Oggi",
            due_today: "Scade Oggi",
            entries: "Voci",
            inflows: "Entrate",
            outflows: "Uscite",
            no_entries_day: "Nessuna voce o fattura per questo giorno.",

            // Reports
            reports_title: "Report",
            reports_subtitle: "Analisi dettagliata delle tue finanze",
            spending_by_category: "Spese per Categoria",
            income_vs_expense: "Entrate vs Spese (Ultimi 6 mesi)",
            not_enough_data: "Dati insufficienti",

            // Planning
            planning_title: "Pianificazione Futura",
            planning_subtitle: "Strumenti per raggiungere la tua libertà finanziaria",
            debt_management: "Gestione Debiti",
            investments: "Investimenti",
            life_goals: "Obiettivi di Vita",
            add_debt: "Aggiungi Debito",
            debt_name_placeholder: "Nome (es: Carta X)",
            value_placeholder: "Valore",
            interest_monthly_placeholder: "Interesse Mensile (%)",
            add: "Aggiungi",
            total_debts: "Totale Debiti",
            snowball_strategy: "La Tua Lista (Strategia Palla di Neve)",
            snowball_desc: "Consigliamo di pagare prima i debiti con interessi più alti o valori più bassi.",
            no_debts: "Nessun debito registrato. Congratulazioni!",
            interest_rate_month: "% p.m.",
            compound_interest_sim: "Simulatore di Interesse Composto",
            initial_investment: "Investimento Iniziale",
            monthly_contribution: "Contributo Mensile",
            interest_rate_year: "Tasso di Interesse (% annuo)",
            time_years: "Tempo (anni)",
            total_accumulated: "Totale Accumulato",
            total_invested: "Totale Investito",
            yield_interest: "Rendimento (Interessi)",
            goals_coming_soon: "Presto potrai creare obiettivi visivi per comprare la tua casa, auto o fare quel viaggio da sogno.",

            // Income
            income_title: "Reddito",
            income_subtitle: "Gestisci le tue entrate e stipendi",
            new_income_button: "Nuovo Reddito",
            total_received_general: "Totale Ricevuto (Generale)",
            this_month: "Questo Mese",
            income_history: "Cronologia Entrate",
            export: "Esporta",
            danger_zone: "Zona di Pericolo",
            delete_transactions: "Elimina Transazioni",
            delete_transactions_desc: "Rimuove solo la cronologia finanziaria.",
            delete_cards: "Elimina Carte",
            delete_cards_desc: "Rimuove tutte le carte registrate.",
            delete_all: "Elimina TUTTO (Reset App)",
            delete_all_desc: "Rimuove tutti i dati, profilo e impostazioni. Irreversibile.",
            delete_confirmation_title: "Sei assolutamente sicuro?",
            delete_confirmation_desc: "Questa azione non può essere annullata. Eliminerà permanentemente i dati selezionati.",
            type_delete_instruction: "Digita DELETAR per confermare",
            erase: "Cancella",
            backup_success: "Backup esportato con successo!",
            wrong_confirmation: "Parola di conferma errata.",
            data_deleted: "Dati cancellati con successo! Ricaricamento...",
        },
    };

    const t = (key: string, params?: Record<string, string | number>) => {
        let translation = translations[language][key] || key;
        if (params) {
            Object.entries(params).forEach(([key, value]) => {
                translation = translation.replace(`{${key}}`, String(value));
            });
        }
        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, locale: locales[language] }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
